[book]
authors = ["Héctor Ramón Jiménez"]
language = "en"
multilingual = false
src = "src"
title = "iced — A Cross-Platform GUI Library for Rust"

[output.html]
mathjax-support = false
git-repository-url = "https://github.com/iced-rs/book/tree/master"
edit-url-template = "https://github.com/iced-rs/book/edit/master/{path}"

[output.html.playground]
runnable = false
